name: hik_player_android
description: Android implementation of the hik_player plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=2.10.0"

flutter:
  plugin:
    implements: hik_player
    platforms:
      android:
        package: top.jawa0919
        pluginClass: HikPlayerPlugin
        dartPluginClass: HikPlayerAndroid

dependencies:
  flutter:
    sdk: flutter
  hik_player_platform_interface:
    path: ../hik_player_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ^2.4.0
